// src/components/Notifications.vue
<script lang="ts" setup>
import {onMounted, onUnmounted, ref} from "vue";
import {AddNotification, Notification} from "../interfaces/notifications.ts";
import {listen, UnlistenFn} from "@tauri-apps/api/event";
import {SEND_NOTIFICATION} from "../utils/events-names.ts";
import {CircleCheck, Info, OctagonX} from "lucide-vue-next";

const notifications = ref<Notification[]>([])

let unsubscribe: UnlistenFn;
onMounted(async () => {
    unsubscribe = await listen<AddNotification>(SEND_NOTIFICATION, (e) => {
        const id = Date.now();
        notifications.value.unshift({
            message: e.payload.message,
            id: id,
            type: e.payload.type
        });

        setTimeout(() => {
            notifications.value = notifications.value.filter(n => n.id !== id)
        }, 4000);
    })
})
onUnmounted(() => {
    unsubscribe();
})
</script>

<template>
    <div class="notifications-center flex column gap10 align-center">
        <div v-for="notification in notifications" :key="notification.id"
             class="notification b-shadow flex align-center gap10 border-r-small {{notification.type}}">
            <Info v-if="notification.type === 'info'" :size="16"/>
            <OctagonX v-else-if="notification.type === 'error'" :size="16"/>
            <CircleCheck v-else-if="notification.type === 'success'" :size="16"/>
            <span>{{ notification.message }}</span>
        </div>
    </div>
</template>

<style lang="scss" scoped>
.notifications-center {
    position: fixed;
    top: 20px;
    left: 0;
    right: 0;
    z-index: 300;
    pointer-events: none;

    .notification {
        pointer-events: all;
        padding: 10px;
        font-size: 0.9em;
        animation: forwards popupFromTop 0.3s;

        &.info {
            background: var(--color-background-scroll);
            color: var(--color-font-light);
        }
    }

    @keyframes popupFromTop {
        from {
            transform: translateY(-100%);
        }
    }
}
</style>

// src/components/notifications/Notifications.tsx
import "./Notifications.scss"
import {useEffect, useState} from "react";
import {listen} from "@tauri-apps/api/event";
import {CircleCheck, Info, OctagonX} from "lucide-react";

export type NotificationsProps = {}

export type Notification = {
    message: string,
    id: number,
    type: "success" | "error" | "info"
}

export type AddNotification = {
    message: string,
    type: "success" | "error" | "info"
}

export const SEND_NOTIFICATION = "ui:add_notification";

function Notifications(_props: NotificationsProps) {
    const [notifications, setNotifications] = useState<Notification[]>([]);

    useEffect(() => {
        const unsubscribe = listen<AddNotification>(SEND_NOTIFICATION, (e) => {
            const id = Date.now();
            setNotifications(old => [{
                message: e.payload.message,
                id: id,
                type: e.payload.type
            }, ...old]);

            setTimeout(() => {
                setNotifications(old => old.filter(n => n.id !== id));
            }, 4000);
        });

        return () => {
            const unsub = async () => {
                let fn = await unsubscribe
                fn();
            }
            unsub();
        }
    }, []);

    return <div className="notifications-center flex column gap10 align-center">
        {notifications.map(notification =>
            <div key={notification.id}
                 className={`notification b-shadow flex align-center gap10 border-r-small ${notification.type}`}>
                {notification.type === "info" && <Info size={16}/>}
                {notification.type === "error" && <OctagonX size={16}/>}
                {notification.type === "success" && <CircleCheck size={16}/>}
                <span>{notification.message}</span>
            </div>
        )}
    </div>
}

export default Notifications;
